export const SCATTER_ACTIONS = {
    CONNECT   : 'SCATTER/CONNECT',
    CONNECTED : 'SCATTER/CONNECTED',
    CONNECTION_ERROR: 'SCATTER/ERRORS/CONNECTION_ERROR',

    LOGIN: 'SCATTER/LOGIN',
    GET_WALLET: 'SCATTER/GET_WALLET',
    SEND_TOKEN: 'SCATTER/SEND_TOKEN',

    LOGIN_ERROR: 'SCATTER/ERRORS/LOGIN_ERROR',
    AUTH_ERROR: 'SCATTER/ERRORS/AUTH_ERROR',
    SEND_TOKEN_ERROR: 'SCATTER/ERRORS/SEND_TOKEN_ERROR',
};

export const connectScatter    = () => ({type: SCATTER_ACTIONS.CONNECT});
export const connectedScatter  = () => ({type: SCATTER_ACTIONS.CONNECTED});
export const connectionError   = () => ({type: SCATTER_ACTIONS.CONNECTION_ERROR});

